stages:
  data_ingestion:
    cmd: python src/deepclassifier/components/data_ingestion.py
    deps:
      - src/deepclassifier/components/data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/PetImages


  prepare_base_model:
    cmd: python src/deepclassifier/components/prepare_base_model.py
    deps:
      - src/deepclassifier/components/prepare_base_model.py
      - configs/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/deepclassifier/components/training.py
    deps:
      - src/deepclassifier/components/training.py
      - src/deepclassifier/components/prepare_callback.py
      - configs/config.yaml
      - artifacts/data_ingestion/PetImages
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5

  